class BuiltinContest {
  final String adifName;
  final String displayName;
  const BuiltinContest({required this.adifName, required this.displayName});
}

// Full Wavelog contest list — merged from Wavelog DB migrations + ADIF standard
// major contests. Sorted alphabetically. "Other / Custom" is NOT here; it is
// pinned separately at the top of the picker UI.
const List<BuiltinContest> kBuiltinContests = [
  BuiltinContest(adifName: '10-10-SPRINT',        displayName: '10-10 Int. 10-10 Day Sprint'),
  BuiltinContest(adifName: '10-10-FALL-CW',       displayName: '10-10 Int. Fall Contest, CW'),
  BuiltinContest(adifName: '10-10-FALL-DIGITAL',  displayName: '10-10 Int. Fall Contest, Digital'),
  BuiltinContest(adifName: '10-10-OPEN-SEASON',   displayName: '10-10 Int. Open Season PSK Contest'),
  BuiltinContest(adifName: '10-10-SPRING-CW',     displayName: '10-10 Int. Spring Contest, CW'),
  BuiltinContest(adifName: '10-10-SPRING-DIGITAL',displayName: '10-10 Int. Spring Contest, Digital'),
  BuiltinContest(adifName: '10-10-SUMMER-PHONE',  displayName: '10-10 Int. Summer Contest, SSB'),
  BuiltinContest(adifName: '10-10-WINTER-PHONE',  displayName: '10-10 Int. Winter Contest, SSB'),
  BuiltinContest(adifName: 'A1CLUB-AWT',          displayName: 'A1Club AWT'),
  BuiltinContest(adifName: 'AC-QSO-PARTY',        displayName: 'Atlantic Canada QSO Party'),
  BuiltinContest(adifName: 'AGCW-QRP',            displayName: 'AGCW QRP/QRP Party'),
  BuiltinContest(adifName: 'ALL-AFRICA',          displayName: 'Africa All Mode International DX Contest'),
  BuiltinContest(adifName: 'ALL-ASIAN-DX-CW',     displayName: 'All Asian DX, CW'),
  BuiltinContest(adifName: 'ALL-ASIAN-DX-SSB',    displayName: 'All Asian DX, SSB'),
  BuiltinContest(adifName: 'ALRS-UA1DZ-CUP',      displayName: 'UA1DZ Memorial Cup'),
  BuiltinContest(adifName: 'ANZAC',               displayName: 'ANZAC Day Contest'),
  BuiltinContest(adifName: '40-80',               displayName: 'ARI 40/80 Contest'),
  BuiltinContest(adifName: 'ARI-40-80',           displayName: 'ARI 40-80 Meter Contest'),
  BuiltinContest(adifName: 'ARI-DX',              displayName: 'ARI DX Contest'),
  BuiltinContest(adifName: 'ARRL-10',             displayName: 'ARRL 10-Meter Contest'),
  BuiltinContest(adifName: 'ARRL-DIGI',           displayName: 'ARRL Inter. Digital Contest'),
  BuiltinContest(adifName: 'ARRL-DX-CW',          displayName: 'ARRL DX Contest, CW'),
  BuiltinContest(adifName: 'ARRL-DX-SSB',         displayName: 'ARRL DX Contest, SSB'),
  BuiltinContest(adifName: 'ARRL-HPM-150',         displayName: 'ARRL Hiram Percy Maxim Birthday'),
  BuiltinContest(adifName: 'ARRL-SS-CW',          displayName: 'ARRL Sweepstakes, CW'),
  BuiltinContest(adifName: 'ARRL-SS-SSB',         displayName: 'ARRL Sweepstakes, SSB'),
  BuiltinContest(adifName: 'ARRL-VHF-JAN',        displayName: 'ARRL January VHF Contest'),
  BuiltinContest(adifName: 'ARRL-VHF-SEP',        displayName: 'ARRL September VHF Contest'),
  BuiltinContest(adifName: 'ARSI-VU-DX',          displayName: 'ARSI VU DX Contest'),
  BuiltinContest(adifName: 'BALKAN-HF',            displayName: 'Balkan HF Contest'),
  BuiltinContest(adifName: 'BALTIC-CONTEST',       displayName: 'Baltic Contest'),
  BuiltinContest(adifName: 'BUCURESTI-DIGITAL',    displayName: 'Bucharest Digital Contest'),
  BuiltinContest(adifName: 'CP-QSO-PARTY',         displayName: 'Canadian Prairies QSO Party'),
  BuiltinContest(adifName: 'CQ-VHF-DIGI',          displayName: 'CQ Worldwide VHF Digital Contest'),
  BuiltinContest(adifName: 'CQ-VHF-SSBCW',         displayName: 'CQ Worldwide VHF SSB/CW Contest'),
  BuiltinContest(adifName: 'CQ-WPX-CW',            displayName: 'CQ WPX, CW'),
  BuiltinContest(adifName: 'CQ-WPX-RTTY',          displayName: 'CQ WPX, RTTY'),
  BuiltinContest(adifName: 'CQ-WPX-SSB',           displayName: 'CQ WPX, SSB'),
  BuiltinContest(adifName: 'CQ-WW-CW',             displayName: 'CQ Worldwide DX, CW'),
  BuiltinContest(adifName: 'CQ-WW-RTTY',           displayName: 'CQ Worldwide DX, RTTY'),
  BuiltinContest(adifName: 'CQ-WW-SSB',            displayName: 'CQ Worldwide DX, SSB'),
  BuiltinContest(adifName: 'CQMMDX',               displayName: 'CQMM DX Contest'),
  BuiltinContest(adifName: 'CQWW-DIGI',             displayName: 'CQ WW Digi / LABRE-RS Digi Contest'),
  BuiltinContest(adifName: 'CQP',                   displayName: 'Collegiate QSO Party'),
  BuiltinContest(adifName: '9A-DX',                 displayName: 'Croatian DX Contest'),
  BuiltinContest(adifName: 'DARC-10',               displayName: 'DARC 10-Meter Contest'),
  BuiltinContest(adifName: 'XMAS',                  displayName: 'DARC Christmas Contest'),
  BuiltinContest(adifName: 'DIG-QSO-PARTY',         displayName: 'DIG QSO Party'),
  BuiltinContest(adifName: 'DRCG-WW-RTTY',          displayName: 'DRCG WW RTTY Contest'),
  BuiltinContest(adifName: 'EA-MAJESTAD-CW',        displayName: 'King of Spain, CW (EA-MAJESTAD)'),
  BuiltinContest(adifName: 'EA-MAJESTAD-SSB',       displayName: 'King of Spain, SSB (EA-MAJESTAD)'),
  BuiltinContest(adifName: 'EARTTY',                displayName: 'EA RTTY Contest'),
  BuiltinContest(adifName: 'EANET-SPRINT',          displayName: 'EANET Sprint'),
  BuiltinContest(adifName: 'ECLIPSE-QSO',           displayName: 'Solar Eclipse QSO Party'),
  BuiltinContest(adifName: 'EU-HF',                 displayName: 'EU HF Championship'),
  BuiltinContest(adifName: 'EUDXC',                 displayName: 'European Union DX Contest'),
  BuiltinContest(adifName: 'EURASIA-CHAMP',         displayName: 'EurAsia HF Championship'),
  BuiltinContest(adifName: 'F9AA-CW',               displayName: 'F9AA Cup, CW'),
  BuiltinContest(adifName: 'F9AA-DIGI',             displayName: 'F9AA Cup, PSK'),
  BuiltinContest(adifName: 'F9AA-SSB',              displayName: 'F9AA Cup, SSB'),
  BuiltinContest(adifName: 'FIELD-DAY',             displayName: 'Field Day'),
  BuiltinContest(adifName: 'FIRAC-CONTEST',         displayName: 'FIRAC HF Contest'),
  BuiltinContest(adifName: 'FRAPR-10M',             displayName: 'FRAPR 10M Contest'),
  BuiltinContest(adifName: 'FT-CHALLENGE',          displayName: 'FT Challenge'),
  BuiltinContest(adifName: 'GC',                    displayName: 'Yuri Gagarin International DX Contest'),
  BuiltinContest(adifName: 'GUNUNGJATI',            displayName: 'Gunung Jati DX Contest'),
  BuiltinContest(adifName: 'HA3NS-SPRINT',          displayName: 'HA3NS Sprint Memorial Contest'),
  BuiltinContest(adifName: 'HAM-SPIRIT',            displayName: 'Ham Spirit Contest, CW'),
  BuiltinContest(adifName: 'HAM-SPIRIT-SSB',        displayName: 'Ham Spirit Contest, SSB'),
  BuiltinContest(adifName: 'HARC-QSOP',             displayName: 'HARC Anniversary QSO Party'),
  BuiltinContest(adifName: 'HOLYLAND',              displayName: 'IARC Holyland Contest'),
  BuiltinContest(adifName: 'IARU-HF',               displayName: 'IARU HF World Championship'),
  BuiltinContest(adifName: 'ICWC-MST',              displayName: 'ICWC Medium Speed Test'),
  BuiltinContest(adifName: 'IG-WW-RY',              displayName: 'IG-RY World Wide RTTY Contest'),
  BuiltinContest(adifName: 'INDEXA-QSOP',           displayName: 'INDEXA Worldwide QSO Party'),
  BuiltinContest(adifName: 'IRTS-CONTEST',          displayName: 'IRTS Counties Contest (2m / 70cm)'),
  BuiltinContest(adifName: 'IRTS-80-CONTEST',       displayName: 'IRTS 80m Counties Contest'),
  BuiltinContest(adifName: 'ISLAND-QSO-PARTY',      displayName: 'U.S. Islands QSO Party'),
  BuiltinContest(adifName: 'JARTS-WW-RTTY',         displayName: 'JARTS WW RTTY Contest'),
  BuiltinContest(adifName: 'K1USNSST',              displayName: 'K1USN Slow Speed Test'),
  BuiltinContest(adifName: 'KALBAR CONTEST',         displayName: 'Kalbar Contest'),
  BuiltinContest(adifName: 'KANHAM',                displayName: 'KANHAM Contest'),
  BuiltinContest(adifName: 'KCJ-TOPBAND',           displayName: 'KCJ Topband Contest'),
  BuiltinContest(adifName: 'KING-OF-SPAIN-CW',      displayName: 'King of Spain, CW'),
  BuiltinContest(adifName: 'KING-OF-SPAIN-RTTY',    displayName: 'King of Spain, RTTY'),
  BuiltinContest(adifName: 'KING-OF-SPAIN-SSB',     displayName: 'King of Spain, SSB'),
  BuiltinContest(adifName: 'LABRE-DX',              displayName: 'LABRE DX Contest'),
  BuiltinContest(adifName: 'MAKROTHEN-RTTY',        displayName: 'Makrothen RTTY Contest'),
  BuiltinContest(adifName: 'MDC-QSO-PARTY',         displayName: 'Maryland-DC QSO Party'),
  BuiltinContest(adifName: 'MCD-QSO-PARTY',         displayName: 'Marconi Club ARI Loano QSO Party Day'),
  BuiltinContest(adifName: 'MEMORIAL-CONTEST',      displayName: 'NZART Memorial Contest'),
  BuiltinContest(adifName: 'MINITEST-40',           displayName: 'Mini-Test 40'),
  BuiltinContest(adifName: 'MINITEST-80',           displayName: 'Mini-Test 80'),
  BuiltinContest(adifName: 'MMC-HF-CW',             displayName: 'Marconi Memorial HF Contest'),
  BuiltinContest(adifName: 'MYDX-SSB-CONTEST',      displayName: 'Malaysia DX Contest'),
  BuiltinContest(adifName: 'NAQP-CW',               displayName: 'NA QP, CW'),
  BuiltinContest(adifName: 'NAQP-RTTY',             displayName: 'NA QP, RTTY'),
  BuiltinContest(adifName: 'NAQP-SSB',              displayName: 'NA QP, SSB'),
  BuiltinContest(adifName: 'NCCC-FIESTA',           displayName: 'NCCC 55th Anniversary Fiesta'),
  BuiltinContest(adifName: 'NCCC-SPRINT-CW',        displayName: 'NCCC Sprint / Sprint Ladder'),
  BuiltinContest(adifName: 'NCCC-SPRINT-FT4',       displayName: 'NCCC FT4 Sprint'),
  BuiltinContest(adifName: 'NRAU-10',               displayName: 'NRAU 10m Activity Contest'),
  BuiltinContest(adifName: 'NRRL-MGM',              displayName: 'NRRL MGM Weekend Contest'),
  BuiltinContest(adifName: 'OCEANIA-DX-CW',         displayName: 'Oceania DX, CW'),
  BuiltinContest(adifName: 'OCEANIA-DX-SSB',        displayName: 'Oceania DX, SSB'),
  BuiltinContest(adifName: 'OK-DX-RTTY',            displayName: 'OK DX RTTY Contest'),
  BuiltinContest(adifName: 'PACCDIGI',              displayName: 'Dutch PACCdigi Contest'),
  BuiltinContest(adifName: 'PBDX-CONTEST',          displayName: 'Pajajaran Bogor DX Contest'),
  BuiltinContest(adifName: 'POC',                   displayName: 'Portable Operations Challenge'),
  BuiltinContest(adifName: 'RAEM',                  displayName: 'RAEM Contest'),
  BuiltinContest(adifName: 'RADIO-160',             displayName: 'Russian 160-Meter DX Contest'),
  BuiltinContest(adifName: 'RADIO-ONY',             displayName: 'Old New Year Contest'),
  BuiltinContest(adifName: 'RADIO-POPOV',           displayName: 'Popov Memorial Contest'),
  BuiltinContest(adifName: 'RADIO-WW-RTTY',         displayName: 'Russian RTTY WW Contest'),
  BuiltinContest(adifName: 'RADIO-YL-OM',           displayName: 'Russian YL/OM Contest'),
  BuiltinContest(adifName: 'RCC-CUP',               displayName: 'RCC Cup'),
  BuiltinContest(adifName: 'RSGB-80M-AUT',          displayName: 'RSGB 80m Autumn Series'),
  BuiltinContest(adifName: 'RSGB-FT4',              displayName: 'RSGB FT4 Contest'),
  BuiltinContest(adifName: 'RSGB-HQP',              displayName: 'RSGB Hope QSO Party'),
  BuiltinContest(adifName: 'RTTYOPS-WEEKSPRINT',    displayName: 'RTTYOPS Weeksprint'),
  BuiltinContest(adifName: 'RTTYOPS-WEEKEND-SPRINT',displayName: 'RTTYOPS Weekend Sprint'),
  BuiltinContest(adifName: 'RTTYOPS-WW-RTTY',       displayName: 'SCRY/RTTYOps WW DX RTTY Contest'),
  BuiltinContest(adifName: 'RUS-WW-DIGI',           displayName: 'Russian WW Digital Contest'),
  BuiltinContest(adifName: 'RUS-WW-MM',             displayName: 'Russian WW MultiMode Contest'),
  BuiltinContest(adifName: 'RUS-WW-PSK',            displayName: 'Russian PSK WW Contest'),
  BuiltinContest(adifName: 'SA10M',                 displayName: 'South America 10 Meter Contest'),
  BuiltinContest(adifName: 'SAC-CW',                displayName: 'Scandinavian Activity, CW'),
  BuiltinContest(adifName: 'SAC-SSB',               displayName: 'Scandinavian Activity, SSB'),
  BuiltinContest(adifName: 'SACW',                  displayName: 'South American Integration Contest CW'),
  BuiltinContest(adifName: 'SARL-HF-CW',            displayName: 'SARL HF CW Contest'),
  BuiltinContest(adifName: 'SARL-HF-DIGI',          displayName: 'SARL HF Digital Contest'),
  BuiltinContest(adifName: 'SARL-HF-SSB',           displayName: 'SARL HF Phone Contest'),
  BuiltinContest(adifName: 'SARTG-NY-RTTY',         displayName: 'SARTG New Year RTTY Contest'),
  BuiltinContest(adifName: 'SEC-QSO-PARTY',         displayName: 'SEC QSO Party'),
  BuiltinContest(adifName: 'SLOW-CW-QSO-PARTY',    displayName: 'Marconi Club ARI Loano Slow CW QSO Party'),
  BuiltinContest(adifName: 'SP-DX',                 displayName: 'SP DX Contest, SSB'),
  BuiltinContest(adifName: 'SP-DX-RTTY',            displayName: 'SP DX Contest, RTTY'),
  BuiltinContest(adifName: 'STAYHOME',              displayName: 'COVID-19 Radio Communication Event'),
  BuiltinContest(adifName: 'STEW-PERRY',            displayName: 'Stew Perry Topband Challenge'),
  BuiltinContest(adifName: 'TA-HF-SSB',             displayName: 'Turkey HF SSB Contest'),
  BuiltinContest(adifName: 'TEN-TEN',               displayName: 'Ten-Ten International Contest'),
  BuiltinContest(adifName: 'TESLA-HF',              displayName: 'TESLA Memorial HF CW Contest'),
  BuiltinContest(adifName: 'TIPALAYO DX CONTEST',   displayName: 'Tipalayo DX Contest'),
  BuiltinContest(adifName: 'TISZACUP',              displayName: 'Tisza Cup CW Contest'),
  BuiltinContest(adifName: 'TNPOTA',                displayName: 'Tennessee State Parks on the Air'),
  BuiltinContest(adifName: 'TRC-DIGI',              displayName: 'TRC Digi Contest'),
  BuiltinContest(adifName: 'TRC-DX',                displayName: 'TRC DX Contest'),
  BuiltinContest(adifName: 'TSPOTA',                displayName: 'Texas State Parks on the Air'),
  BuiltinContest(adifName: 'UBA-DX-CW',             displayName: 'UBA DX, CW'),
  BuiltinContest(adifName: 'UBA-DX-SSB',            displayName: 'UBA DX, SSB'),
  BuiltinContest(adifName: 'UBA-ON-2M',             displayName: 'UBA ON Contest, 2m'),
  BuiltinContest(adifName: 'UBA-ON-6M',             displayName: 'UBA ON Contest, 6m'),
  BuiltinContest(adifName: 'UBA-ON-CW',             displayName: 'UBA ON Contest, CW'),
  BuiltinContest(adifName: 'UBA-ON-SSB',            displayName: 'UBA ON Contest, SSB'),
  BuiltinContest(adifName: 'UBA-PSK63-PREFIX',      displayName: 'UBA PSK63 Prefix Contest'),
  BuiltinContest(adifName: 'UBA-SPRING-CONTEST',    displayName: 'UBA Spring Contest'),
  BuiltinContest(adifName: 'UFT-QRP',               displayName: 'UFT QRP Contest'),
  BuiltinContest(adifName: 'UKEI-DX',               displayName: 'UK/EI DX Contest'),
  BuiltinContest(adifName: 'UKEICC-80M',            displayName: 'UKEICC 80m Contest'),
  BuiltinContest(adifName: 'UN-DX',                 displayName: 'UN DX Contest'),
  BuiltinContest(adifName: 'UR-DX-DIGI',            displayName: 'Ukrainian DX DIGI Contest'),
  BuiltinContest(adifName: 'UR-DX-RTTY',            displayName: 'Ukrainian DX Classic RTTY Contest'),
  BuiltinContest(adifName: 'URCDX',                 displayName: 'URC DX RTTY Contest'),
  BuiltinContest(adifName: 'VHF-NAMSS',             displayName: 'North American Meteor Scatter Sprint'),
  BuiltinContest(adifName: 'VK-SHIRES',             displayName: 'VK Shires Contest'),
  BuiltinContest(adifName: 'VT-QSO-PARTY',          displayName: 'Vermont QSO Party'),
  BuiltinContest(adifName: 'WAE-CW',                displayName: 'WAE DX, CW'),
  BuiltinContest(adifName: 'WAE-RTTY',              displayName: 'WAE DX, RTTY'),
  BuiltinContest(adifName: 'WAE-SSB',               displayName: 'WAE DX, SSB'),
  BuiltinContest(adifName: 'WA-SALMON-RUN',         displayName: 'Washington State Salmon Run'),
  BuiltinContest(adifName: 'WAPC-DX',               displayName: 'Worked All Provinces of China DX Contest'),
  BuiltinContest(adifName: 'WIA-AUSTRALIADAY',      displayName: 'Australia Day Contest'),
  BuiltinContest(adifName: 'WINTER-FIELD-DAY',      displayName: 'Winter Field Day'),
  BuiltinContest(adifName: 'WRT',                   displayName: 'Weekly RTTY Test'),
  BuiltinContest(adifName: 'WW-PMC',                displayName: 'WW PMC Contest'),
  BuiltinContest(adifName: 'WWHC',                  displayName: 'World Wide Holyland Contest'),
  BuiltinContest(adifName: 'WWPDX',                 displayName: 'World Wide Argentina DX Contest'),
  BuiltinContest(adifName: 'WWSA',                  displayName: 'GACW WWSA CW DX Contest'),
  BuiltinContest(adifName: 'WWSAC',                 displayName: 'Worldwide Sideband Activity Contest'),
  BuiltinContest(adifName: 'YARC-QSO-PARTY',        displayName: 'YARC QSO Party'),
  BuiltinContest(adifName: 'YB DX CONTEST',         displayName: 'YB DX Contest, SSB'),
  BuiltinContest(adifName: 'YB-DX-CONTEST',         displayName: 'YB DX RTTY Contest'),
  BuiltinContest(adifName: 'YL-OM',                 displayName: 'YLRL YL-OM Contest'),
  BuiltinContest(adifName: 'YOTA',                  displayName: 'YOTA Contest'),
  BuiltinContest(adifName: 'ZL-SPRINT',             displayName: 'ZL Sprint'),
];
